version: '3'
services:
  ddns:
    build: .
    environment:
      ACCOUNT_ID: ${ACCOUNT_ID}
      AUTH_TOKEN: ${AUTH_TOKEN}
      DSN: ${DSN}
      RECORD_NAME: ${RECORD_NAME}
      ZONE_NAME: ${ZONE_NAME}
    restart: always
    command: 'node dist/main.js'
    logging:
      options:
        max-size: "10m"
        max-file: "5"
      driver: json-file
