name: Docker Image CI

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  release-package:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: pmorelli92/github-container-registry-build-push@2.0.0
      name: Build and Publish latest service image
      with:
        github-push-secret: ${{ secrets.GITHUB_TOKEN }}
        docker-image-name: cf-ts-ddns
        docker-image-tag: ${{ github.ref_name	}} # optional
        # dockerfile-path: ./src/svc/Dockerfile # optional
        # build-context: ./src/svc # optional
